/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bulbyvr.jank;

import java.util.function.Supplier;
import java.io.*;
public class Foo {
    public static void doSomething(Supplier<Integer> fun) {
        System.out.println(fun.get());
    }
    public static void test() {
        doSomething(() -> 1);
    }
}